import type { AdminProfileResponse, AdminPermissionResponse } from '../../services/api-type';
import dayjs from 'dayjs';

// 模拟管理员个人信息数据
export const mockAdminProfile: AdminProfileResponse = {
  admin_id: 'admin_001',
  account: 'admin001',
  name: '管理员',
  nickname: '管理员昵称',
  gender: 'man',
  email: 'admin@lenovo.com',
  avatar: null,
  status: '正常',
  created_at: dayjs().subtract(1, 'year').format('YYYY-MM-DD HH:mm:ss'),
  last_login_time: dayjs().subtract(1, 'hour').format('YYYY-MM-DD HH:mm:ss'),
  identities: [
    {
      admin_identity_id: 'admin_identity_001',
      identity_id: 'identity_001',
      identity_name: '超级管理员',
      identity_code: 'SUPER_ADMIN',
      expire_time: null,
      status: '启用',
    },
    {
      admin_identity_id: 'admin_identity_002',
      identity_id: 'identity_002',
      identity_name: '商品管理员',
      identity_code: 'PRODUCT_MANAGER',
      expire_time: dayjs().add(30, 'day').format('YYYY-MM-DD HH:mm:ss'),
      status: '启用',
    },
  ],
  permissions: [
    {
      identity_permission_id: 'perm_001',
      permission_id: 'permission_001',
      permission_name: '用户管理',
      permission_type: 'menu',
      module: '用户管理',
      parent_id: null,
    },
    {
      identity_permission_id: 'perm_002',
      permission_id: 'permission_002',
      permission_name: '商品管理',
      permission_type: 'menu',
      module: '商品管理',
      parent_id: null,
    },
    {
      identity_permission_id: 'perm_003',
      permission_id: 'permission_003',
      permission_name: '订单管理',
      permission_type: 'menu',
      module: '订单管理',
      parent_id: null,
    },
    {
      identity_permission_id: 'perm_004',
      permission_id: 'permission_004',
      permission_name: '查看用户列表',
      permission_type: 'api',
      module: '用户管理',
      parent_id: 'permission_001',
    },
    {
      identity_permission_id: 'perm_005',
      permission_id: 'permission_005',
      permission_name: '编辑用户',
      permission_type: 'api',
      module: '用户管理',
      parent_id: 'permission_001',
    },
  ],
  categories: [
    {
      admin_product_category_id: 'admin_category_001',
      category_id: 'category_001',
      category_name: '笔记本电脑',
      category_code: 'LAPTOP',
      status: '启用',
    },
    {
      admin_product_category_id: 'admin_category_002',
      category_id: 'category_002',
      category_name: '台式电脑',
      category_code: 'DESKTOP',
      status: '启用',
    },
    {
      admin_product_category_id: 'admin_category_003',
      category_id: 'category_003',
      category_name: '手机',
      category_code: 'PHONE',
      status: '启用',
    },
  ],
};

// 模拟管理员权限数据
export const mockAdminPermissions: AdminPermissionResponse = {
  permissions: [
    {
      id: 'permission_001',
      name: '用户管理',
      code: 'USER_MANAGE',
      type: 'menu',
      module: '用户管理',
      parentId: null,
    },
    {
      id: 'permission_002',
      name: '商品管理',
      code: 'PRODUCT_MANAGE',
      type: 'menu',
      module: '商品管理',
      parentId: null,
    },
    {
      id: 'permission_003',
      name: '订单管理',
      code: 'ORDER_MANAGE',
      type: 'menu',
      module: '订单管理',
      parentId: null,
    },
    {
      id: 'permission_004',
      name: '查看用户列表',
      code: 'USER_LIST',
      type: 'api',
      module: '用户管理',
      parentId: 'permission_001',
    },
    {
      id: 'permission_005',
      name: '编辑用户',
      code: 'USER_EDIT',
      type: 'api',
      module: '用户管理',
      parentId: 'permission_001',
    },
    {
      id: 'permission_006',
      name: '删除用户',
      code: 'USER_DELETE',
      type: 'api',
      module: '用户管理',
      parentId: 'permission_001',
    },
    {
      id: 'permission_007',
      name: '查看商品列表',
      code: 'PRODUCT_LIST',
      type: 'api',
      module: '商品管理',
      parentId: 'permission_002',
    },
    {
      id: 'permission_008',
      name: '编辑商品',
      code: 'PRODUCT_EDIT',
      type: 'api',
      module: '商品管理',
      parentId: 'permission_002',
    },
  ],
  permissionsTree: [
    {
      id: 'permission_001',
      name: '用户管理',
      code: 'USER_MANAGE',
      type: 'menu',
      module: '用户管理',
      parentId: null,
      children: [
        {
          id: 'permission_004',
          name: '查看用户列表',
          code: 'USER_LIST',
          type: 'api',
          module: '用户管理',
          parentId: 'permission_001',
        },
        {
          id: 'permission_005',
          name: '编辑用户',
          code: 'USER_EDIT',
          type: 'api',
          module: '用户管理',
          parentId: 'permission_001',
        },
        {
          id: 'permission_006',
          name: '删除用户',
          code: 'USER_DELETE',
          type: 'api',
          module: '用户管理',
          parentId: 'permission_001',
        },
      ],
    },
    {
      id: 'permission_002',
      name: '商品管理',
      code: 'PRODUCT_MANAGE',
      type: 'menu',
      module: '商品管理',
      parentId: null,
      children: [
        {
          id: 'permission_007',
          name: '查看商品列表',
          code: 'PRODUCT_LIST',
          type: 'api',
          module: '商品管理',
          parentId: 'permission_002',
        },
        {
          id: 'permission_008',
          name: '编辑商品',
          code: 'PRODUCT_EDIT',
          type: 'api',
          module: '商品管理',
          parentId: 'permission_002',
        },
      ],
    },
    {
      id: 'permission_003',
      name: '订单管理',
      code: 'ORDER_MANAGE',
      type: 'menu',
      module: '订单管理',
      parentId: null,
    },
  ],
  identities: [
    {
      id: 'identity_001',
      name: '超级管理员',
      code: 'SUPER_ADMIN',
      description: '拥有系统所有权限的管理员',
      isSystem: true,
    },
    {
      id: 'identity_002',
      name: '商品管理员',
      code: 'PRODUCT_MANAGER',
      description: '负责商品管理的管理员',
      isSystem: true,
    },
    {
      id: 'identity_003',
      name: '订单管理员',
      code: 'ORDER_MANAGER',
      description: '负责订单管理的管理员',
      isSystem: false,
    },
  ],
  categories: [
    {
      id: 'category_001',
      name: '笔记本电脑',
      code: 'LAPTOP',
    },
    {
      id: 'category_002',
      name: '台式电脑',
      code: 'DESKTOP',
    },
    {
      id: 'category_003',
      name: '手机',
      code: 'PHONE',
    },
    {
      id: 'category_004',
      name: '平板电脑',
      code: 'TABLET',
    },
  ],
};


